lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    public_key: '%env(JWT_SECRET_KEY)%'
    pass_phrase: '%env(default::JWT_PASSPHRASE)%'
    token_ttl: 1800  # 30 minutes (meilleure pratique de sécurité)
    encoder:
        signature_algorithm: HS256
