lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    public_key: '%env(JWT_SECRET_KEY)%'
    pass_phrase: '%env(default::JWT_PASSPHRASE)%'
    token_ttl: 604800  # 7 jours (dur√©e de session confortable)
    encoder:
        signature_algorithm: HS256
